XS:
  name: size/XS
  lines: 0
  color: 3CBF00
S:
  name: size/S
  lines: 100
  color: 5D9801
M:
  name: size/M
  lines: 300
  color: 7F7203
L:
  name: size/L
  lines: 1000
  color: A14C05
XL:
  name: size/XL
  lines: 5000
  color: C32607
XXL:
  name: size/XXL
  lines: 10000
  color: E50009