codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "30...100"

  status:
    project:
      default:
        informational: true # do not fail check
        only_pulls: true
    patch: false

ignore:
  - "pkg/action/flags.go"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
