codecov:
  require_ci_to_pass: true
  branch: main
  allow_pseudo_compare: true
  allow_coverage_offsets: true

ignore:
  - cmd
  - pkg/action/commands.go

coverage:
  precision: 2
  round: down
  range: "20...70"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false

flag_management:
  default_rules:
    carryforward: true

flags:
  integration:
    carryforward: true
