name: Docs

on:
  release:
    types: [ published ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/use-app-token@v2
        id: token
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Trigger helmwave/docs workflow
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.token.outputs.BOT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: "docs",
              workflow_id: "generate-new-version.yml",
              ref: "main",
              inputs: {
                tag: process.env.GITHUB_TAG,
              },
            })
        env:
          GITHUB_TAG: ${{ github.event.release.tag_name }}
