name: Test GoReleaser config

on:
  pull_request:
    branches:
      - main
    paths:
      - ".goreleaser.yml"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Test GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: check
